{
 "title": "All",
 "time": { "from": "now-15d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Active Alerts",
   "type": "graph",
   "description": "0 is good. 1 means the alert is active.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}",
     "legendFormat": "{{exported_job}}--{{original_name}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "{exported_job=\"cronjob_readmemory\",__name__!=\"push_time_seconds\",__name__!=\"last_success_unixtime\",__name__!=\"script_duration_seconds\",__name__!=\"next_expected_unixtime\",__name__!~\"avg3h.*\",__name__!=\"RUN_LAST_SECONDS_AGO\",__name__!=\"RUN_NEXT_SECONDS_AGO\",__name__!=\"std_dev\",__name__!~\"stat__.*\", alertname=\"\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 }, "content": "# Custom Data Objects (CDOs)" },
  {
   "title": "Contacts.Vivastream",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours of records created.\n\nINXPO is our virtual event management vendor.\n\nc.ix_created will not match the count returned by DATA_HOURLY_ELOQUA_FORMS_created{exported_job=\"integration_form_inxpo\"} because form submissions include both new records and modifications to current records.\n\nEvery time there is a non-unique pair of show key and offer, the alert remains active for 24 hours after the data was received (meaning if an event was watched on monday and on-demand submissions continued to be received until Friday, we would receive alerts all week despite how there may have been only one non-unique pair).",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=\"visor_eloqua_cdo_contacts_vivastream\",__name__!=\"push_time_seconds\",__name__!=\"last_success_unixtime\",__name__!=\"script_duration_seconds\",__name__!=\"next_expected_unixtime\",__name__!~\"stat__.*\",__name__!~\"avg3h.*\", alertname=\"\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Contacts.INXPO",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours of records created.\n\nINXPO is our virtual event management vendor.\n\nc.ix_created will not match the count returned by DATA_HOURLY_ELOQUA_FORMS_created{exported_job=\"integration_form_inxpo\"} because form submissions include both new records and modifications to current records.\n\nEvery time there is a non-unique pair of show key and offer, the alert remains active for 24 hours after the data was received (meaning if an event was watched on monday and on-demand submissions continued to be received until Friday, we would receive alerts all week despite how there may have been only one non-unique pair).",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=\"visor_eloqua_cdo_contacts_inxpo\",__name__!=\"push_time_seconds\",__name__!=\"last_success_unixtime\",__name__!=\"script_duration_seconds\",__name__!=\"next_expected_unixtime\",__name__!~\"stat__.*\",__name__!~\"avg3h.*\", alertname=\"\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Contacts.LeadType",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=~\".*contacts_leadtype.*$\",__name__!=\"push_time_seconds\",__name__!=\"last_success_unixtime\",__name__!=\"script_duration_seconds\",__name__!=\"next_expected_unixtime\",__name__!~\"stat__.*\",__name__!~\"avg3h.*\", alertname=\"\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Contacts.Inquiries",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours of records created.\n\nINXPO is our virtual event management vendor.\n\nc.ix_created will not match the count returned by DATA_HOURLY_ELOQUA_FORMS_created{exported_job=\"integration_form_inxpo\"} because form submissions include both new records and modifications to current records.\n\nEvery time there is a non-unique pair of show key and offer, the alert remains active for 24 hours after the data was received (meaning if an event was watched on monday and on-demand submissions continued to be received until Friday, we would receive alerts all week despite how there may have been only one non-unique pair).",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=\"visor_eloqua_cdo_contacts_inquiries\",__name__!=\"push_time_seconds\",__name__!=\"last_success_unixtime\",__name__!=\"script_duration_seconds\",__name__!=\"next_expected_unixtime\",__name__!~\"stat__.*\",__name__!~\"avg3h.*\",__name__!~\"srcofupld.*\",__name__!~\"formsource.*\", alertname=\"\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Contacts.Inquiries F_FormData_Source1 not upload",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours of records created.\n\nINXPO is our virtual event management vendor.\n\nc.ix_created will not match the count returned by DATA_HOURLY_ELOQUA_FORMS_created{exported_job=\"integration_form_inxpo\"} because form submissions include both new records and modifications to current records.\n\nEvery time there is a non-unique pair of show key and offer, the alert remains active for 24 hours after the data was received (meaning if an event was watched on monday and on-demand submissions continued to be received until Friday, we would receive alerts all week despite how there may have been only one non-unique pair).",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=\"visor_eloqua_cdo_contacts_inquiries\",__name__=~\"formsource.*\",__name__!~\"formsource_upload.*\", alertname=\"\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Contacts.Inquiries F_FormData_Source1 from upload",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours of records created.\n\nINXPO is our virtual event management vendor.\n\nc.ix_created will not match the count returned by DATA_HOURLY_ELOQUA_FORMS_created{exported_job=\"integration_form_inxpo\"} because form submissions include both new records and modifications to current records.\n\nEvery time there is a non-unique pair of show key and offer, the alert remains active for 24 hours after the data was received (meaning if an event was watched on monday and on-demand submissions continued to be received until Friday, we would receive alerts all week despite how there may have been only one non-unique pair).",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=\"visor_eloqua_cdo_contacts_inquiries\",__name__=~\"formsource_upload.*\", alertname=\"\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "visor_eloqua_cdo tacticless_offer",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=~\"visor_eloqua_cdo.*$\",__name__!=\"push_time_seconds\",__name__=~\".*tacticless_.*$\",__name__!~\".*srcofupld.*$\"}",
     "legendFormat": "{{exported_job}}: {{__name__}}"
    }
   ]
  },
  {
   "title": "Contacts.Inquiries missingMembership",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=\"visor_eloqua_cdo_contacts_inquiries\",__name__!=\"push_time_seconds\",__name__=~\"srcofupldnot.*membership.*$\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Contacts.Inquiries non-upload sourced records; Other metrics",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=~\"visor_eloqua_cdo.*$\",__name__=~\"srcofupldnot_.*\",__name__!~\"srcofupldnot_.*valid.*\",__name__!=\"srcofupldnot_crtd\",__name__!=\"srcofupldnot_new_avg_age_mins\",__name__!~\"srcofupldnot_tactic.*\",__name__!~\"srcofupldnot_offer.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "visor_eloqua_cdo created",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=~\"visor_eloqua_cdo.*$\",__name__!=\"push_time_seconds\",__name__=\"crtd\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "visor_eloqua_cdo modified",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=~\"visor_eloqua_cdo.*$\",__name__!=\"push_time_seconds\",__name__=\"mdfd\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "visor_eloqua_cdo offerless_tactic",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=~\"visor_eloqua_cdo.*$\",__name__!=\"push_time_seconds\",__name__=~\".*offerless_.*$\",__name__!~\".*srcofupld.*$\"}",
     "legendFormat": "{{exported_job}}: {{__name__}}"
    }
   ]
  },
  {
   "title": "visor_eloqua_cdo campaign tactic_format_bad",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=~\"visor_eloqua_cdo.*$\",__name__!=\"push_time_seconds\",__name__=\"tactic_format_bad\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "visor_eloqua_cdo new_avg_age_mins",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=~\"visor_eloqua_cdo.*$\",__name__!=\"push_time_seconds\",__name__=\"new_avg_age_mins\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "visor_eloqua_cdo email blank",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=~\"visor_eloqua_cdo.*\",__name__!=\"push_time_seconds\",__name__=\"email_blank\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "visor_eloqua_cdo offer blank",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"offer_blank\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "visor_eloqua_cdo tactic blank",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"tactic_blank\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "visor_eloqua_cdo campaign offer_format_bad",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=~\"visor_eloqua_cdo.*$\",__name__!=\"push_time_seconds\",__name__=\"offer_format_bad\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 }, "content": "# Everything Upload" },
  {
   "title": "Contacts.Uploads.Members",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=~\"visor_eloqua_cdo_contacts_uploads_member.*$\",__name__!=\"push_time_seconds\",__name__!=\"last_success_unixtime\",__name__!=\"script_duration_seconds\",__name__!=\"next_expected_unixtime\",__name__!~\"stat__.*\",__name__!~\"avg3h.*\",__name__!~\"offer.*\",__name__!~\"tactic.*\",__name__!~\"new_avg_age_mins.*\", alertname=\"\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Contacts.Inquiries upload sourced records; valid campaign metrics",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=~\"visor_eloqua_cdo.*$\",__name__=~\"srcofupld_.*valid.*\",__name__!~\"srcofupld_.*missingmembership.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Contacts.Inquiries upload sourced records; Campaign missing memberships",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=~\"visor_eloqua_cdo.*$\",__name__=~\"srcofupld_.*missing_membership.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Contacts.Inquiries upload sourced records; Other campaign metrics",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=~\"visor_eloqua_cdo.*$\",__name__=~\"srcofupld_offer.*\",__name__!~\"srcofupld_.*missingmembership.*\",__name__!~\"srcofupld_.*valid.*\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{exported_job=~\"visor_eloqua_cdo.*$\",__name__=~\"srcofupld_tactic.*\",__name__!~\"srcofupld_.*missingmembership.*\",__name__!~\"srcofupld_.*valid.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Contacts.Inquiries upload sourced records; Other metrics",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=~\"visor_eloqua_cdo.*$\",__name__=~\"srcofupld_.*\",__name__!~\"srcofupld_.*valid.*\",__name__!=\"srcofupld_crtd\",__name__!=\"srcofupld_new_avg_age_mins\",__name__!~\"srcofupld_tactic.*\",__name__!~\"srcofupld_offer.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Uploaded records in Contacts.Uploads.Members compared to Contacts.Inquiries",
   "type": "graph",
   "description": "These should follow each other closely. \nProcessing time of records from Contacts.Uploads.Members to reach Contacts.Inquiries is about 6 hours. If the timespan is larger than that, then processing is slow. \nIf Contacts.Inquiries never reaches the same count as Contacts.Uploads.Members, then processing is losing records.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "srcofupld_crtd", "legendFormat": "Inquiries_{{__name__}}" },
    {
     "expr": "{exported_job=\"visor_eloqua_cdo_contacts_uploads_members\",__name__=\"crtd\"}",
     "legendFormat": "Uploads_{{__name__}}"
    }
   ]
  },
  {
   "title": "Contacts created in Eloqua from an upload in the past 24 hours",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cntcts_crtd_frm_c_uploads_members_last_24_hrs",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "visor_eloqua_form (upload_wizard)",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours of form submissions for each of these forms.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"integration_form_upload_wizard.*$\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 }, "content": "# Other" },
  {
   "title": "script_duration_seconds (CDOs)",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "script_duration_seconds{exported_job=~\"visor_eloqua_cdo.*\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 }, "content": "# Eloqua Forms" },
  {
   "title": "visor_eloqua_form (starts with \"integration_form_c\")",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours of form submissions for each of these forms.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"integration_form_c.*$\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "visor_eloqua_form (starts with \"integration_form_a\" or \"d\" or \"l\")",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours of form submissions for each of these forms.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"integration_form_a.*$\",__name__!=\"integration_form_automated_campaigns\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{__name__=~\"integration_form_d.*$\",__name__!~\"integration_form_dynamic_form.*\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{__name__=~\"integration_form_l.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "DATA_HOURLY_ELOQUA_FORMS_created (starts with \"intergration_form_t\" or \"v\")",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours of form submissions for each of these forms.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"integration_form_t.*$\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{__name__=~\"integration_form_v.*$\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "DATA_HOURLY_ELOQUA_FORMS_created (starts with \"intergration_form_s\" or \"i\")",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours of form submissions for each of these forms.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"integration_form_s.*$\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{__name__=~\"integration_form_i.*$\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "visor_eloqua_form (other)",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours of form submissions for each of these forms.\n\nIn an effort to declutter, I have hidden all metrics that have only had 0 values. To see them, open this metric in Prometheus, where no hide criteria is applied.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"integration_form_.*\",__name__!~\"integration_form_c.*$\",__name__!~\"integration_form_upload_wizard.*$\",__name__!~\"service.*$\",__name__!~\"notification.*$\",__name__!~\"integration_form_a.*$\",__name__!~\"integration_form_d.*$\",__name__!~\"integration_form_t.*$\",__name__!~\"integration_form_v.*\",__name__!~\"integration_form_s.*\",__name__!~\"integration_form_i.*\",__name__!~\"integration_form_l.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "visor_eloqua_form (starts with \"service_form_copyto\")",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours of form submissions for each of these forms.",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"service_form_copyto.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "visor_eloqua_form (starts with \"service_form_sendto\")",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours of form submissions for each of these forms.",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"service_form_sendto.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "visor_eloqua_form (starts with \"service\")",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours of form submissions for each of these forms.",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"service.*\",__name__!~\"service_form_copyto.*\",__name__!~\"service_form_sendto.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "visor_eloqua_form (starts with \"notification\")",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours of form submissions for each of these forms.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"notification.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "integration_form_automated_campaigns",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours of form submissions for each of these forms.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"integration_form_auto.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "integration_form_dynamic_form UX Status Percents",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours of form submissions for each of these forms.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"integration_form_dynam.*\",__name__=~\".*prcnt_of_ttl$\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "integration_form_dynamic_form counts",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours of form submissions for each of these forms.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"integration_form_dynam.*\",__name__=~\".*cnt$\"}",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "integration_form_dynamic_form", "legendFormat": "{{__name__}}" }
   ]
  },
  { "type": "text", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 }, "content": "# URL Monitoring" },
  {
   "title": "Is URL down (alerting)",
   "type": "graph",
   "description": "0 is good. 1 means the site is down.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg({exported_job=\"visor_url\",__name__!=\"push_time_seconds\",__name__!=\"last_success_unixtime\",__name__!=\"script_duration_seconds\",__name__!=\"next_expected_unixtime\",__name__!~\"avg3h.*\",__name__!=\"RUN_LAST_SECONDS_AGO\",__name__!=\"RUN_NEXT_SECONDS_AGO\",__name__!=\"std_dev\",__name__!~\"stat__.*\", alertname=\"\", monitor=\"true\"}) by (__name__)",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Is URL down (not alert triggering)",
   "type": "graph",
   "description": "0 is good. 1 means the site is down.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg({exported_job=\"visor_url\",__name__!=\"push_time_seconds\",__name__!=\"last_success_unixtime\",__name__!=\"script_duration_seconds\",__name__!=\"next_expected_unixtime\",__name__!~\"avg3h.*\",__name__!=\"RUN_LAST_SECONDS_AGO\",__name__!=\"RUN_NEXT_SECONDS_AGO\",__name__!=\"std_dev\",__name__!~\"stat__.*\", alertname=\"\", monitor!=\"true\"}) by (__name__)",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "script_duration_seconds (other)",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "script_duration_seconds{exported_job!~\"visor_eloqua_cdo.*\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 }, "content": "# General Segments" },
  {
   "title": "visor_eloqua_segment",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=\"visor_eloqua_segment\",__name__!=\"push_time_seconds\",__name__!=\"last_success_unixtime\",__name__!=\"script_duration_seconds\",__name__!=\"next_expected_unixtime\",__name__!~\"avg3h.*\",__name__!=\"RUN_LAST_SECONDS_AGO\",__name__!=\"RUN_NEXT_SECONDS_AGO\",__name__!=\"std_dev\",__name__!~\"stat__.*\",__name__!~\"cntcts_eng_sta_.*\",__name__!=\"cntcts_mdfd_last_24_hrs\", __name__!=\"cntcts_crtd_last_24_hrs\", __name__!=\"cntcts_crtd_frm_c_uploads_members_last_24_hrs\", __name__!=\"cntcts_in_elq\", alertname=\"\"}>=0",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 }, "content": "# Engagement Status" },
  {
   "title": "Engagement Status changes in the past 24 hours",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"cntcts_eng_sta_.*24_hrs\"}>=0",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "All Engagement Statuses together",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"cntcts_eng_sta_.*\",__name__!~\"cntcts_eng_sta_.*24_hrs\"}>=0",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "cntcts_eng_sta_most_active",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cntcts_eng_sta_most_active", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "cntcts_eng_sta_lapsing",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cntcts_eng_sta_lapsing", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "cntcts_eng_sta_lapsed",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cntcts_eng_sta_lapsed", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "cntcts_eng_sta_inactive",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cntcts_eng_sta_inactive\t", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "cntcts_eng_sta_pending",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cntcts_eng_sta_pending", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "cntcts_eng_sta_invalid",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cntcts_eng_sta_invalid", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "cntcts_eng_sta_internal",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cntcts_eng_sta_internal", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "cntcts_eng_sta_active",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cntcts_eng_sta_active", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "cntcts_eng_sta_unconventional",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cntcts_eng_sta_unconventional", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "cntcts_eng_sta_one_time_reset",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cntcts_eng_sta_one_time_reset", "legendFormat": "{{__name__}}" }
   ]
  },
  { "type": "text", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 }, "content": "# Shared Lists" },
  {
   "title": "Shared Lists",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=~\"visor_eloqua_shared.*\",__name__!=\"push_time_seconds\",__name__!=\"last_success_unixtime\",__name__!=\"script_duration_seconds\",__name__!=\"next_expected_unixtime\",__name__!~\"stat__.*\",__name__!~\"avg3h.*\", alertname=\"\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 }, "content": "# Contact Database" },
  {
   "title": "Total Contacts in Eloqua",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"cntcts_in_elq\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Total Contacts in Eloqua",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "{__name__=\"cntcts_in_elq\",custom_label=\"\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Contacts created in Eloqua in the past 24 hours",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cntcts_crtd_last_24_hrs", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Contacts modified in Eloqua in the past 24 hours",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cntcts_mdfd_last_24_hrs", "legendFormat": "{{__name__}}" }
   ]
  },
  { "type": "text", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 }, "content": "# Other" },
  {
   "title": "stat__next_runtime__second_ago",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "stat__next_runtime__second_ago", "legendFormat": "{{exported_job}}" }
   ]
  },
  {
   "title": "cdos_marked_for_deletion_cnt",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=\"visor_eloqua_cdo_cleanup\",__name__!=\"push_time_seconds\",__name__!=\"last_success_unixtime\",__name__!=\"script_duration_seconds\",__name__!=\"next_expected_unixtime\",__name__!~\"avg3h.*\",__name__!=\"RUN_LAST_SECONDS_AGO\",__name__!=\"RUN_NEXT_SECONDS_AGO\",__name__!=\"std_dev\",__name__!~\"stat__.*\",alertname=\"\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "script_duration_seconds (CDOs)",
   "type": "graph",
   "description": "These metrics are pulled from the past 24 hours.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "script_duration_seconds", "legendFormat": "{{exported_job}}" }
   ]
  }
 ]
}