# almost the entirety of this yaml was copied from examples in the Sys Scale repo. Examples most prominently used:
# https://REDACTED.redhat.com/REDACTED/REDACTED-luigi/blob/master/.configs/build.yaml


apiVersion: v1
kind: Template
parameters:

# - name: APP_NAME
#   description: The application name used to group the template's objects.
#   required: true
#   value: managedplatflasktest

# - name: APP_DESCRIPTION
  # description: The description of the app being implemented by this template
  # required: true

# - name: OPENSHIFT_NAMESPACE
#   description: The OpenShift project that the template is being applied to
#   required: true
#   value: visor 

# - name: BRANCH
#   description: git branch in the repo
#   required: true
#   value: develop

# - name: REPO_URI
#   description: The uri to the git repo used for this project  # 
#   required: true
#   value: https://REDACTED.redhat.com/REDACTED/visor.git

# - name: REPO_SECRET_NAME
#   description: Name of secret containing the credentials to pull from project repo
#   required: true
#   value: REDACTED

# - name: REPO_USER
#   description: User to pull from project repo
#   required: true

# - name: REPO_PASSWORD
#   description: Password of user to pull from project repo
#   required: true

# - name: IMAGE_BASE_URI
#   description: The uri of the base image in red hat container catalog https://access.redhat.com/containers
#   required: true
#   value: REDACTED.redhat.com/rhscl/python-36-rhel7

# - name: IMAGE_SOURCE_FOUNDATION
#   description: The first portion of the image tag name
#   required: true
#   value: REDACTED.redhat.com # REDACTED.redhat.com

# - name: IMAGE_S2I_SECRET
#   description: The secret used by the builder to access the registry
#   required: true
#   value: REDACTED # REDACTED  # this secret was created automatically for me

# - name: TEMPLATE_TRIGGERED_BY
#   description: The user that is commiting this OC command to create the template
#   required: true

- name: APP_NAME  # I opted to use all parameters that were set locally--set by defaults, rather than by the BuildApp.groovy so that I'd know exactly what values were being passed.
  value: managedplatflasktest
- name: IMAGE_BASE_URI  # The uri of the base image in red hat container catalog https://access.redhat.com/containers; ex. REDACTED.redhat.com/rhscl/python-36-rhel7
  value: REDACTED.redhat.com/rhscl/python-36-rhel7
- name: OPENSHIFT_NAMESPACE   # The OpenShift project that the template is being applied to
  value: visor
- name: REPO_URI
  value: https://REDACTED.redhat.com/REDACTED/visor.git
- name: REPO_SECRET_NAME  # Name of secret to contain the credentials to pull from project repo
  value: REDACTED
- name: IMAGE_S2I_SECRET  # The secret used by the builder to access the registry
  value: REDACTED # REDACTED  # this secret was created automatically for me
- name: IMAGE_SOURCE_FOUNDATION  # The first portion of the image tag name
  value: REDACTED.redhat.com


#  parameters from /REDACTED/REDACTED/src/com/redhat/mktg_ops/pipeline/BuildApp.groovy
# Why not use the parameters already in BuildApp? I didn't like the naming convention
# - name: APP_NAME  # The application name used to group the template's objects. # defined from /REDACTED/REDACTED/src/com/redhat/mktg_ops/pipeline/BuildApp.groovy; which is determined by the JJB parameter
- name: NAME_SPACE
- name: BRANCH  # the only parameter that I have permitted to be set by BuildApp.groovy. # git branch in the repo  # defined from /REDACTED/REDACTED/src/com/redhat/mktg_ops/pipeline/BuildApp.groovy; which is determined by the JJB parameter
# - name: REPO_URI
- name: OUTPUT_IMAGE
- name: REGISTRY_SECRET


metadata:
  name: ${APP_NAME}
  # annotations:
    # description: ${APP_DESCRIPTION}
  template: ${APP_NAME}

labels:
  # createdBy: ${TEMPLATE_TRIGGERED_BY}
  app: ${APP_NAME}

objects:

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
    namespace: ${OPENSHIFT_NAMESPACE}
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
  spec:
    output:
      to:
        kind: DockerImage
        name: ${IMAGE_SOURCE_FOUNDATION}/${OPENSHIFT_NAMESPACE}/${APP_NAME}:${BRANCH}  # ex: REDACTED.redhat.com/REDACTED/audit-service:3.1.0-SNAPSHOT
      pushSecret:
        name: ${IMAGE_S2I_SECRET}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /${APP_NAME}
      git:
        ref: ${BRANCH}
        uri: ${REPO_URI}
      sourceSecret:
        name: ${REPO_SECRET_NAME}
      type: Git
      noCache: true  # I added this in hopes that I'd be able to trigger a new build and it'd pull the latest commit rather than the first commit that the build used.
    strategy:
      sourceStrategy:
        env:
          - name: HTTP_PROXY  # Looks like this mojo doc says it's required by OHC: https://REDACTED.redhat.com/docs/DOC-000
            value: REDACTED.redhat.com:000
          - name: HTTPS_PROXY
            value: REDACTED.redhat.com:000
        from:
          kind: DockerImage
          name: ${IMAGE_BASE_URI}
      type: Source